# Cloud Run environment variables for AI Hub backend
# Copy this file to cloudrun.env.yaml and fill in real values,
# then deploy with: --env-vars-file ai-hub/infra/cloudrun.env.yaml

# Core
SECRET_KEY: "change-me"
LOG_LEVEL: "INFO"

# API
# Comma-separated list of allowed origins (no brackets)
BACKEND_CORS_ORIGINS: "https://your-domain.com,https://admin.your-domain.com"

# Database (Cloud SQL or external Postgres via private IP or SSL proxy)
# Use async driver for SQLAlchemy engine creation
DATABASE_URI: "postgresql+asyncpg://user:password@host:5432/aihub"

# Redis (e.g. Memorystore for Redis via private IP and VPC connector)
REDIS_HOST: ""
REDIS_PORT: "6379"
REDIS_DB: "0"
REDIS_PASSWORD: ""

# Email (optional, for notifications)
SMTP_HOST: ""
SMTP_PORT: ""
SMTP_USER: ""
SMTP_PASSWORD: ""
EMAILS_FROM_EMAIL: "no-reply@your-domain.com"
EMAILS_FROM_NAME: "AI Hub"

# OpenAI (optional; duplicate detection disabled if not set)
OPENAI_API_KEY: ""
OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"

# SLA and duplicate detection
SLA_ANALYST_DAYS: "5"
SLA_FINANCE_DAYS: "5"
SLA_DEVELOPER_DAYS: "5"
DUPLICATE_SIMILARITY_THRESHOLD: "0.8"
IMPROVEMENT_SIMILARITY_THRESHOLD: "0.5"
